version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "9000"
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
