version: "2.7"

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5434:5432" # Change from 5432 to 5434 on the host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
